try {
    print(x)
} catch {
    print("NameError")
}